---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for org.apache.servicecomb.samples.bmi.CalculatorRestEndpoint"
  x-java-interface: "gen.swagger.CalculatorRestEndpointIntf"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /bmi:
    get:
      operationId: "calculate"
      parameters:
      - name: "height"
        in: "query"
        required: false
        type: "number"
        format: "double"
      - name: "weight"
        in: "query"
        required: false
        type: "number"
        format: "double"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/BMIViewObject"
definitions:
  BMIViewObject:
    type: "object"
    properties:
      result:
        type: "number"
        format: "double"
      instanceId:
        type: "string"
      callTime:
        type: "string"
    x-java-class: "org.apache.servicecomb.samples.bmi.BMIViewObject"
